// Assets e insígnias do Sistema Gamificado de Conquistas WAnime

export const BADGE_IMAGE_MAP: Record<string, string> = {
  intro_catalog: '/badges/badge_intro_catalog.webp',
  intro_first_ep: '/badges/badge_intro_first_ep.webp',
  intro_watching: '/badges/badge_intro_watching.webp',
  intro_plan_to_watch: '/badges/badge_intro_plan_to_watch.webp',
  intro_first_rating: '/badges/badge_intro_first_rating.webp',
  intro_completed: '/badges/badge_intro_completed.webp',
  intro_short_anime: '/badges/badge_intro_short_anime.webp',
  intro_movie_fan: '/badges/badge_intro_movie_fan.webp',
  eps_10: '/badges/badge_eps_10.webp',
  eps_50: '/badges/badge_eps_50.webp',
  genre_comedy: '/badges/badge_genre_comedy.webp',
  genre_multi: '/badges/badge_genre_multi.webp',
  genre_romance: '/badges/badge_genre_romance.webp',
  eps_150: '/badges/badge_eps_150.webp',
  eps_300: '/badges/badge_eps_300.webp',
  col_finished_5: '/badges/badge_col_finished_5.webp',
  col_finished_15: '/badges/badge_col_finished_15.webp',
  genre_shonen: '/badges/badge_genre_shonen.webp',
  genre_isekai: '/badges/badge_genre_isekai.webp',
  genre_scifi: '/badges/badge_genre_scifi.webp',
  genre_suspense: '/badges/badge_genre_suspense.webp',
  genre_sports: '/badges/badge_genre_sports.webp',
  genre_supernatural: '/badges/badge_genre_supernatural.webp',
  spec_retro_classic: '/badges/badge_spec_retro_classic.webp',
  spec_ongoing_tracker: '/badges/badge_spec_ongoing_tracker.webp',
  rating_critic: '/badges/badge_rating_critic.webp',
  spec_arcs: '/badges/badge_spec_arcs.webp',
  eps_750: '/badges/badge_eps_750.webp',
  eps_1500: '/badges/badge_eps_1500.webp',
  col_finished_30: '/badges/badge_col_finished_30.webp',
  col_finished_60: '/badges/badge_col_finished_60.webp',
  rating_masterpiece: '/badges/badge_rating_masterpiece.webp',
  genre_eclectic_gold: '/badges/badge_genre_eclectic_gold.webp',
  col_finished_short_series: '/badges/badge_col_finished_short_series.webp',
  spec_studio_ufotable: '/badges/badge_spec_studio_ufotable.webp',
  spec_grand_line: '/badges/badge_spec_grand_line.webp',
  eps_3000: '/badges/badge_eps_3000.webp',
  col_finished_100: '/badges/badge_col_finished_100.webp',
  spec_single_500: '/badges/badge_spec_single_500.webp',
  rating_supreme_critic: '/badges/badge_rating_supreme_critic.webp',
  genre_master: '/badges/badge_genre_master.webp',
  eps_5000: '/badges/badge_eps_5000.webp',
  spec_king_shonen: '/badges/badge_spec_king_shonen.webp',
  col_finished_200: '/badges/badge_col_finished_200.webp',
  col_archivist: '/badges/badge_col_archivist.webp',
};

export function getBadgeImageUrl(badgeId: string): string {
  return BADGE_IMAGE_MAP[badgeId] || '/badges/badge_intro_catalog.webp';
}

